<?php

/**
 * PluginsbEcomProductDescriptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomProductDescriptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomProductDescriptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomProductDescription');
    }
}