<?php

/**
 * PluginsbEcomCheckoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomCheckoutTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomCheckoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomCheckout');
    }
}