<?php

/**
 * PluginsbEcomProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @author Giles Smith <tech@superrb.com>
 */
class PluginsbEcomProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sbEcomProduct');
    }
		
		/**
		 * Returns all featured products
		 * 
		 * @return Doctrine_Collection 
		 */
		public static function getFeaturedProducts($category = null)
		{
			return self::getInstance()->findByIsFeatured(1);
		}
		
		/**
		 * Returns all categories that are being used by shop products
		 * 
		 * @return Doctrine_Collection
		 */
		public static function getProductCategories()
		{
			$fast = sfConfig::get('app_a_fasthydrate', false);
			return Doctrine_Query::create()
							->select('c.id, c.slug, c.name')
							->from('aCategory c')
							->innerJoin('c.EcomProducts p')
							->execute(array(), $fast ? Doctrine::HYDRATE_ARRAY : Doctrine::HYDRATE_RECORD);
		}
		
		/**
		 * Returns all product in a given category
		 * 
		 * @param aCategory $category 
		 * @return Doctrine_Collection
		 */
		public static function getProductsInCategory(aCategory $category)
		{
			$fast = sfConfig::get('app_a_fasthydrate', false);
			return Doctrine_Query::create()
							->select('p.id, p.title, p.cost, p.tax, p.slug')
							->from('sbEcomProduct p')
							->innerJoin('p.Categories c')
							->where('c.id = ?', $category->getId())
							->execute(array(), $fast ? Doctrine::HYDRATE_ARRAY : Doctrine::HYDRATE_RECORD);
		}
		
		/**
		 * Find an aCategory by it's Slug
		 * 
		 * @param string $slug
		 * @return aCategory 
		 */
		public static function getProductCategoryBySlug($slug)
		{
			return aCategoryTable::getInstance()->findOneBySlug($slug);
		}
		
		/**
		 * Return a product from a given slug
		 * 
		 * @param string $slug
		 * @return sbEcomProduct
		 */
		public static function getProductBySlug($slug)
		{
			return self::getInstance()->findOneBySlug($slug);
		}
		
		/**
		 * Return a product from a given id
		 *
		 * @param integer $id
		 * @return sbEcomProduct
		 */
		public static function getProductById($id)
		{
			return self::getInstance()->findOneById($id);
		}
}