<?php

/**
 * PluginsbEcomAddToBasketWithOptionSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomAddToBasketWithOptionSlotTable extends aSlotTable
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginsbEcomAddToBasketWithOptionSlotTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginsbEcomAddToBasketWithOptionSlot');
  }
  
  public static function convertOptionValuesToSelectOptions($slot)
  { 
    // configure options
    $options = array();
    
    if(!($slot instanceof sbEcomAddToBasketWithOptionSlot))
    {
      return $options;
    }
    
    $slotValues = $slot->getArrayValue();
    $values = json_decode($slotValues['option_value']);
    
    if($values)
    {
      foreach($values as $key => $value)
      {
        if($value->cost < 0) { $string = ' (-' . sbEcomToolkit::costFormat(0 - $value->cost) . ')'; } else { $string = ' (+' . sbEcomToolkit::costFormat($value->cost) . ')'; }
        if($value->cost == 0) { $string = '' ; }
        $options[$value->value] = $value->value . ', Ref: ' . $value->reference . $string;
      }
    }
    
    return $options;
  }
}