<?php

/**
 * PluginsbEcomBasketProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsbEcomBasketProduct extends BasesbEcomBasketProduct
{
	public function getCost()
	{
		return round($this->getItemCost() * $this->getQuantity(), 2);
	}
	
	public function getTax()
	{
		return round((($this->getItemTax() / 100) * $this->getItemCost()) * $this->getQuantity(), 2);
	}
	
	public function getPostage()
	{
		return round($this->getPostageCost() * $this->getQuantity(), 2);
	}
	
	public function getTotalCost()
	{
		return round($this->getCost() + $this->getTax(), 2);
	}
}