<?php

/**
 * PluginsbEcomProductsSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomProductsSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomProductsSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomProductsSlot');
    }
}