<?php

/**
 * PluginsbEcomProductSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomProductSlotTable extends aSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomProductSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomProductSlot');
    }
}