<?php

/**
 * PluginsbEcomBrandTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomBrand');
    }
}