<?php

/**
 * PluginsbEcomCheckout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsbEcomCheckout extends BasesbEcomCheckout
{
	public function getCost()
	{
		$cost = 0;
		
		foreach($this->getEcomCheckoutProduct() as $product)
		{
			$cost += $product->getCost();
		}
		
		return $cost;
	}
	
	public function getTax()
	{
		$cost = 0;
		
		foreach($this->getEcomCheckoutProduct() as $product)
		{
			$cost += $product->getTax();
		}
		
		return $cost;
	}
	
	public function getPostage()
	{
		$cost = 0;
		
		foreach($this->getEcomCheckoutProduct() as $product)
		{
			$cost += $product->getPostage();
		}
		
		return $cost;
	}
	
	public function getTotalCost()
	{
		return $this->getCost() + $this->getTax() + $this->getPostage();
	}
}