<?php

/**
 * PluginsbEcomAddToBasketSlotTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomAddToBasketNoQuantitySlotTable extends PluginsbEcomAddToBasketSlotTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomAddToBasketSlotTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomAddToBasketNoQuantitySlot');
    }
}