<?php

/**
 * PluginsbEcomBasketProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomBasketProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sbEcomBasketProduct
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sbEcomBasketProduct');
    }
}