<?php

/**
 * PluginsbEcomProductToASearchDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsbEcomProductToASearchDocumentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsbEcomProductToASearchDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsbEcomProductToASearchDocument');
    }
}