# Basket Engine
sb_ecom_basket:
  url: /
  param: { module: sbEcomBasket, action: index }
  class: aRoute
  
sb_ecom_basket_action:
  url: /:action
  param: { module: sbEcomBasket }
  class: aRoute

# Checkout engine
sb_ecom_checkout:
  url: /
  param: { module: sbEcomCheckout, action: index }
  class: aRoute
  
sb_ecom_checkout_action:
  url: /:action 
  param: { module: sbEcomCheckout }
  class: aRoute
  
sb_ecom_paypal_payments_pro_with_iframe:
  url: /
  param: { module: sbEcomPaypalPaymentsProWithIframe, action index }
  class: aRoute