# Basket Engine
sb_ecom_basket:
  url: /
  param: { module: sbEcomBasket, action: index }
  class: aRoute
  
sb_ecom_basket_action:
  url: /:action
  param: { module: sbEcomBasket }
  class: aRoute

# Checkout engine
sb_ecom_checkout:
  url: /
  param: { module: sbEcomCheckout, action: index }
  class: aRoute
  
sb_ecom_checkout_action:
  url: /:action 
  param: { module: sbEcomCheckout }
  class: aRoute
  
# Routes for the Paypal Payments Pro with Iframe Checkout Module
sb_ecom_paypal_payments_pro_with_iframe:
  url: /
  param: { module: sbEcomPaypalPaymentsProWithIframe, action: index }
  class: aRoute
  
sb_ecom_paypal_payments_pro_with_iframe_notify:
  url: /return/:id
  param: { module: sbEcomPaypalPaymentsProWithIframe, action: return }
  class: aRoute
  
# Checkout engine admin
sb_ecom_checkout_admin:
  class: sfDoctrineRouteCollection
  options:
    model:                sbEcomCheckout
    module:               sbEcomCheckoutAdmin
    prefix_path:          /admin/checkouts
    column:               id
    with_wildcard_routes: true