## YAML Template.
---
default:
  stylesheets:
    - /sbApostropheEcommercePlugin/css/sbApostropheEcommerce.css: { data-asset-group: global }     # sbApostropheEcommercePlugin - Styles
    
  javascripts:
    - /sbApostropheEcommercePlugin/js/sbApostropheEcommerce.js: { data-asset-group: global }
    - /sbApostropheEcommercePlugin/js/jquery.cookie.js: { data-asset-group: global }