generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sbEcomCheckout
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sb_ecom_checkout_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: 'Checkout Orders'
        display: [ payment_reference, contact_firstname, contact_lastname, contact_email, status, _products, _cost, created_at, updated_at ]
        actions: { }
        sort: [ updated_at, desc ]
      filter:
        fields:   [ payment_reference, contact_firstname, contact_lastname, contact_email, status ]
        display:  [ payment_reference, contact_firstname, contact_lastname, contact_email, status ]
      form:    ~
      edit: 
        title: Edit Checkout
        display:
          Order Status: [ status, payment_reference ]
          Products Purchased: [ _products_purchased ]
          Contact: [ contact_title, contact_firstname, contact_lastname, contact_email, contact_telephone, contact_mobile ]
          Delivery Address: [ delivery_street_address, delivery_post_office_box_number, delivery_locality, delivery_region, delivery_postal_code, delivery_country ]
          Billing Address: [ billing_street_address, billing_post_office_box_number, billing_locality, billing_region, billing_postal_code, billing_country ]
      #new:     ~
