options: 
  type: INNODB

# Basket Items attached to session
sbEcomBasketProduct:
  actAs:
    Timestampable: ~
  columns:
    session_id:
      type: varchar(255)
    product_id:
      type: integer
    quantity:
      type: integer
      default: 0
  relations:
    EcomProduct:
      class: aPage
      foreignAlias: EcomBasketProduct
      local: product_id
      foreign: id
      onDelete: CASCADE