options: 
  type: INNODB

# Basket Items attached to session
sbEcomBasketProduct:
  actAs:
    Timestampable: ~
  columns:
    session_id:
      type: varchar(255)
    product_id:
      type: integer
    slot_id:
      type: integer
    quantity:
      type: integer
      default: 0
    item_cost:
      type: float
      default: 0
    postage_cost:
      type: float
      default: 0
    item_tax: 
      type: float
      default: 0
    item_title:
      type: string(255)
    item_reference:
      type: string(255)
  relations:
    EcomProduct:
      class: aPage
      foreignAlias: EcomBasketProduct
      local: product_id
      foreign: id
      onDelete: CASCADE
    EcomSlot:
      class: aSlot
      foreignAlias: EcomBasketProductSlot
      local: slot_id
      foreign: id
      onDelete: CASCADE
  indexes:
    # this is here to make basket clean ups easier
    updated_at: { fields: [ updated_at ] }
    # find users baskets quicker
    session_id: { fields: [ session_id ] }
    
    
sbEcomAddToBasketSlot:
  # Doctrine doesn't produce useful forms with column aggregation inheritance anyway,
  # and slots often use serialization into the value column... the Doctrine forms are not
  # of much use here and they clutter the project
  options:
    symfony:
      form:   false
      filter: false

  # columns:
  #
  # You can add columns here. However, if you do not need foreign key relationships it is
  # often easier to store your data in the 'value' column via serialize(). If you do add columns, 
  # their names must be unique across all slots in your project, so use a unique prefix 
  # for your company.
    
  # This is how we are able to retrieve slots of various types with a single query from
  # a single table
  inheritance:
    extends: aSlot
    type: column_aggregation
    keyField: type
    keyValue: 'sbEcomAddToBasket'
sbEcomProductSlot:
  # Doctrine doesn't produce useful forms with column aggregation inheritance anyway,
  # and slots often use serialization into the value column... the Doctrine forms are not
  # of much use here and they clutter the project
  options:
    symfony:
      form:   false
      filter: false

  # columns:
  #
  # You can add columns here. However, if you do not need foreign key relationships it is
  # often easier to store your data in the 'value' column via serialize(). If you do add columns, 
  # their names must be unique across all slots in your project, so use a unique prefix 
  # for your company.
    
  # This is how we are able to retrieve slots of various types with a single query from
  # a single table
  inheritance:
    extends: aSlot
    type: column_aggregation
    keyField: type
    keyValue: 'sbEcomProduct'

sbEcomProductsSlot:
  # Doctrine doesn't produce useful forms with column aggregation inheritance anyway,
  # and slots often use serialization into the value column... the Doctrine forms are not
  # of much use here and they clutter the project
  options:
    symfony:
      form:   false
      filter: false

  # columns:
  #
  # You can add columns here. However, if you do not need foreign key relationships it is
  # often easier to store your data in the 'value' column via serialize(). If you do add columns, 
  # their names must be unique across all slots in your project, so use a unique prefix 
  # for your company.
    
  # This is how we are able to retrieve slots of various types with a single query from
  # a single table
  inheritance:
    extends: aSlot
    type: column_aggregation
    keyField: type
    keyValue: 'sbEcomProducts'
