options: 
  type: INNODB
  
# The product object
sbEcomProduct:
  actAs:
    Timestampable: ~
    Taggable: ~
    Sluggable:
      unique: true
      fields: [ title ]
      canUpdate: true
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    author_id:
      type: integer
    brand_id:
      type: integer
    title:
      type: string(255)
      notnull: true
      unique: true
    internal_reference:
      type: string(255)
    description:
      type: clob
    cost:
      type: decimal(18)
      scale: 2
      default: 0
    tax:
      type: float
      default: 20
      scale: 4
    postage_weight_or_fixed:
      type: enum
      values: [ weight, fixed, free ]
      default: weight
    postage_weight:
      type: float
      scale: 4
      default: 0
    postage_fixed_cost:
      type: float
      scale: 2
      default: 0
    call_to_buy:
      type: boolean
      default: false
    is_featured:
      type: boolean
      default: false
    is_out_of_stock:
      type: boolean
      default: false
    number_in_stock:
      type: integer
      default: 0
    active: 
      type: boolean
      default: true
  relations:
    Author:
      class: sfGuardUser
      foreignAlias: EcomProductAuthor
      local: author_id
      foreign: id
      onDelete: SET NULL
    ProductDescriptions:
      class: sbEcomProductDescription
      foreignAlias: EcomProductDescriptionProduct
      local: id
      foreign: product_id
    Categories:
      foreignAlias: EcomProductCategories
      class: aCategory
      refClass: sbEcomProductToCategory
      local: ecom_product_id
      foreign: category_id
    Brand:
      foreignAlias: EcomProductBrands
      class: sbEcomBrand
      local: brand_id
      foreign: id
    BasketProduct:
      foreignAlias: EcomBasketProduct
      class: sbEcomBasketProduct
      local: id
      foreign: product_id
      onDelete: CASCADE
    aSearchDocuments:
      class: aSearchDocument
      refClass: sbEcomProductToASearchDocument
      foreign: a_search_document_id
      local: sb_ecom_product_id
  indexes:
    active: { fields: active }
    author: { fields: author_id }
    brand: { fields: brand_id }
    call_to_buy: { fields: call_to_buy }
    tax: { fields: tax }
    postage_weight_or_fixed: { fields: postage_weight_or_fixed }
    is_featured: { fields: is_featured }
    is_out_of_stock: { fields: is_out_of_stock }
    
sbEcomBrand:
  actAs:
    Timestampable: ~
    Taggable: ~
    Sluggable:
      unique: true
      fields: [ title ]
      canUpdate: true
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    author_id:
      type: integer
    title:
      type: string(255)
      notnull: true
      unique: true
    description:
      type: clob
  relations:
    Author:
      class: sfGuardUser
      foreignAlias: EcomBrandAuthor
      local: author_id
      foreign: id
      onDelete: SET NULL
  indexes:
    title: { fields: title }
    author: { fields: author_id }
      
sbEcomProductDescription:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    author_id:
      type: integer
    product_id:
      type: integer
    title:
      type: string(255)
      notnull: true
      unique: true
    description:
      type: clob
  relations:
    Author:
      class: sfGuardUser
      foreignAlias: EcomProductDescriptionAuthor
      local: author_id
      foreign: id
      onDelete: SET NULL
    Product:
      class: sbEcomProduct
      foreignAlias: EcomProductDescriptionProduct
      local: product_id
      foreign: id
      onDelete: CASCADE
    
# Extend the Apostrophe Category to include Relationship     
aCategory:
  relations:
    EcomProducts:
      class: sbEcomProduct
      foreignAlias: EcomProductCategories
      refClass: sbEcomProductToCategory
      local: category_id
      foreign: ecom_product_id

# Link the product to Apostrophe categories
sbEcomProductToCategory:
  columns:
    ecom_product_id:
      type: integer
      primary: true
    category_id:
      type: integer
      primary: true
  relations:
    EcomProduct:
      foreignAlias: EcomProductCategories
      class: sbEcomProduct
      local: ecom_product_id
      onDelete: CASCADE
    Category:
      foreignAlias: EcomProductCategories
      class: aCategory
      local: category_id
      onDelete: CASCADE

# Basket Items attached to session
sbEcomBasketProduct:
  actAs:
    Timestampable: ~
  columns:
    session_id:
      type: varchar(255)
    product_id:
      type: integer
    quantity:
      type: integer
      default: 0
  relations:
    EcomProduct:
      class: sbEcomProduct
      foreignAlias: EcomBasketProduct
      local: product_id
      foreign: id
      onDelete: CASCADE
      
sbEcomProductToASearchDocument:
  columns:
    a_search_document_id:
      type: integer
    # Must be your table name followed by _id
    sb_ecom_product_id:
      type: integer
  relations:
    aSearchDocument:
      local: a_search_document_id
      foreign: id
      class: aSearchDocument
      onDelete: cascade
    sbEcomProduct:
      local: sb_ecom_product_id
      foreign: id
      class: sbEcomProduct
      onDelete: cascade
  options:
    symfony:
      form:   false
      filter: false
    